version: '3.3'

services:
  lab:
    container_name: ppio-lab
    build:
      context: .
      dockerfile: Dockerfile.lab
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - "./:/app"
    env_file:
      - "./.env-docker"
    ports:
      - "9001:9001"

networks:
  default:
    external:
      name: ppio